# Generated by Django 3.1 on 2020-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perportfolio', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='progress',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
