# Generated by Django 3.1 on 2020-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perportfolio', '0003_skills_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='progress',
            field=models.CharField(max_length=3),
        ),
    ]
